### ISSUE TITLE
Video Duration

### ISSUE THREAD

**Issue by Samiul30** [eugeneware/ffmpeg-static#103]
I have downloaded video using ffmpeg-static and ytdl. But the total duration of the video is not showing in my phone. Video is fully downloaded and playable.

**Comment by derhuerst** [comment]
This doesn't seem to be a problem with `ffmpeg-static`, and I cannot give support for ffmpeg itself here. You can get help with using ffmpeg via one of the [official support channels](https://ffmpeg.org/contact.html). Good luck!

In case an ffmpeg binary on your system (e.g. installed via your operating system's package manager) behaves differently than the ffmpeg binary from `ffmpeg-static`, please re-open this Issue.

**Comment by Samiul30** [comment]
I think it's ffmpeg issue. And the duration metadata is 0 in case if it exported by the ffmpeg.

**Comment by derhuerst** [comment]
If you decide to report this via the ffmpeg support channels, make sure to include clear instructions to reproduce the issue: All (relevant) commands you ran, how you tried to play the video on your phone, etc.
