### ISSUE TITLE
Duration Metadata 

### ISSUE THREAD

**Issue by Samiul30** [eugeneware/ffmpeg-static#104]
I am merging video and audio with the following command using ffmpeg-static but the duration metadata is 0 and incase of mobile phone the duration is showing 00:00 though it is normally playable.
` '-i', pipe:3,
    '-i', pipe:4,
    '-map','0:v',
    '-map','1:a',
    '-c:v', 'copy',
    '-c:a', 'libmp3lame',
    '-crf','27',
    '-preset','veryfast',
    '-movflags','frag_keyframe+empty_moov',
    '-f','mp4',
    '-loglevel','error',
    '-'`

**Comment by derhuerst** [comment]
Just like with #103, this doesn't seem to be an issue with `ffmpeg-static` (which just downloads `ffmpeg` binaries), but of [ffmpeg](https://ffmpeg.org) itself.

You can get help with using ffmpeg via one of the [official support channels](https://ffmpeg.org/contact.html). If you report your problem there, please include your ffmpeg version (`ffmpeg --version`) and your operation system and version.
