### ISSUE TITLE
Secure Connection issue (https)

### ISSUE THREAD

**Issue by Timileyin105** [eugeneware/ffmpeg-static#105]
hello i have this error while using ur awesome package

[fferr] [hls @ 0x1a66ec0] Failed to open segment 236 of playlist 0
[fferr] https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.

how do i enable secure transport or enable openssl

thanks

**Comment by derhuerst** [comment]
Please provide more details: operating system, CPU architecture, command that you ran.

**Comment by derhuerst** [comment]
Please re-open if you have more details.
