### ISSUE TITLE
npm install failed: no binary found for architecture on termux OS

### ISSUE THREAD

**Issue by DanielBUBU** [eugeneware/ffmpeg-static#106]
I tried to install the package on temux (linux emulator runs on android) ,but it doesn't work
Is there any method to install it using npm on termux?
![256506501_633165024524825_5126371228518308578_n](https://user-images.githubusercontent.com/54381631/169823524-0e201043-02af-4344-922c-b55729c47ac7.png)

**Comment by derhuerst** [comment]
Can you provide the logs showing what exactly fails?

**Comment by derhuerst** [comment]
related: #28 #29

**Comment by DanielBUBU** [comment]
> Can you provide the logs showing what exactly fails?

If you mean the log file ,I need to know how to export file from emulator first

~/PD_maid $ npm i ffmpeg-static                            [#################.] - reify:agent-base: timing reifyNode: > ffmpeg-static@4.4.1 install                              > node install.js                                                                                                     ffmpeg-static install failed: No binary found for architecture                                                        npm ERR! code 1                                            npm ERR! path /data/data/com.termux/files/home/PD_maid/node_modules/ffmpeg-static                                     npm ERR! command failed                                    npm ERR! command sh -c node install.js                                                                                npm ERR! A complete log of this run can be found in:       npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-05-24T11_51_41_253Z-debug-0.log                         ~/PD_maid $

**Comment by derhuerst** [comment]
Can you provide the output of `node -p 'os.arch()'` & `node -p 'os.platform()'`?

**Comment by DanielBUBU** [comment]
> Can you provide the output of `node -p 'os.arch()'` & `node -p 'os.platform()'`?

~/PD_maid $ node -p 'os.arch()'                            arm64                                                     
~/PD_maid $ node -p 'os.platform()'                        android

**Comment by derhuerst** [comment]
In this case, somebody should investigate if a Linux arm64 ffmpeg binary runs in a Termux environment.

**Comment by derhuerst** [comment]
Closing in favour of #28. If you want to investigate how to get Termux/Android working, please comment there and I'll re-open the Issue.
