### ISSUE TITLE
Failed to install package

### ISSUE THREAD

**Issue by Danjuanlab** [eugeneware/ffmpeg-static#107]
I installed the ffmpeg-static package in vscode, but the installation failed. Judging from the npm log file, it seems to be a related resource 404.Please ask what should I do

```
234 timing reifyNode:node_modules/buffer Completed in 197ms
235 timing reifyNode:node_modules/http-response-object Completed in 207ms
236 timing reifyNode:node_modules/extsprintf Completed in 211ms
237 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 263ms (cache skip)
238 silly audit bulk request failed <h1>404 Not Found</h1>
239 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 1208ms (cache skip)
240 verbose audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
240 verbose audit error     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:95:15
240 verbose audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
240 verbose audit error     at async Map.[getReport] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:337:21)
240 verbose audit error     at async Map.run (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:107:19) {
240 verbose audit error   headers: [Object: null prototype] {
240 verbose audit error     server: [ 'Tengine' ],
240 verbose audit error     'content-type': [ 'text/html; charset=utf-8' ],
240 verbose audit error     'content-length': [ '41' ],
240 verbose audit error     connection: [ 'keep-alive' ],
240 verbose audit error     'strict-transport-security': [ 'max-age=5184000' ],
240 verbose audit error     date: [ 'Sat, 25 Jun 2022 04:17:25 GMT' ],
240 verbose audit error     vary: [ 'Origin' ],
240 verbose audit error     'x-frame-options': [ 'SAMEORIGIN' ],
240 verbose audit error     'x-xss-protection': [ '1; mode=block' ],
240 verbose audit error     'x-content-type-options': [ 'nosniff' ],
240 verbose audit error     'x-download-options': [ 'noopen' ],
240 verbose audit error     'x-readtime': [ '1.33' ],
240 verbose audit error     'content-encoding': [ 'gzip' ],
240 verbose audit error     'ali-swift-global-savetime': [ '1656130645' ],
240 verbose audit error     via: [
240 verbose audit error       'cache28.l2cn1837[27,27,404-1280,M], cache66.l2cn1837[28,0], kunlun1.cn44[43,30,404-1280,C], kunlun1.cn44[35,0]'
240 verbose audit error     ],
240 verbose audit error     age: [ '0' ],
240 verbose audit error     'x-cache': [ 'HIT TCP_MEM_HIT dirn:-2:-2' ],
240 verbose audit error     'x-swift-savetime': [ 'Sat, 25 Jun 2022 04:17:25 GMT' ],
240 verbose audit error     'x-swift-cachetime': [ '1' ],
240 verbose audit error     'x-swift-error': [ 'orig response 4XX error' ],
240 verbose audit error     'timing-allow-origin': [ '*' ],
240 verbose audit error     eagleid: [ '7d4cf79f16561306452883169e' ],
240 verbose audit error     'x-fetch-attempts': [ '1' ],
240 verbose audit error     'x-local-cache-status': [ 'skip' ]
240 verbose audit error   },
240 verbose audit error   statusCode: 404,
240 verbose audit error   code: 'E404',
240 verbose audit error   method: 'POST',
240 verbose audit error   uri: 'https://registry.npmmirror.com/-/npm/v1/security/audits/quick',
240 verbose audit error   body: <Buffer 3c 68 31 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 68 31 3e>,
240 verbose audit error   pkgid: undefined
240 verbose audit error }
241 silly audit error <h1>404 Not Found</h1>
242 timing auditReport:getReport Completed in 1622ms
243 silly audit report null
244 timing reify:audit Completed in 1624ms
245 timing reifyNode:node_modules/@derhuerst/http-basic Completed in 1702ms
246 timing reifyNode:node_modules/crc Completed in 1778ms
247 timing reifyNode:node_modules/http-response-object/node_modules/@types/node Completed in 1864ms
248 timing reifyNode:node_modules/xmlbuilder Completed in 1889ms
249 timing reifyNode:node_modules/node-addon-api Completed in 1920ms
250 timing reify:unpack Completed in 1923ms
251 timing reify:unretire Completed in 0ms
252 timing build:queue Completed in 6ms
253 timing build:link Completed in 0ms
254 info run ffmpeg-static@5.0.0 install node_modules/ffmpeg-static node install.js
255 info run ffmpeg-static@5.0.0 install { code: 3221225786, signal: null }
256 timing reify:rollback:createSparse Completed in 494ms
257 timing reify:rollback:retireShallow Completed in 1ms
258 timing command:i Completed in 214520ms
259 verbose stack Error: command failed
259 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
259 verbose stack     at ChildProcess.emit (node:events:520:28)
259 verbose stack     at maybeClose (node:internal/child_process:1092:16)
259 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
260 verbose pkgid ffmpeg-static@5.0.0
261 verbose cwd C:\Users\zifan\Desktop\elsTools\electron-vite-vue-1.0.0
262 verbose Windows_NT 10.0.22000
263 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "ffmpeg-static"
264 verbose node v16.14.0
265 verbose npm  v8.3.1
266 error code 3221225786
```

**Comment by derhuerst** [comment]
> […] it seems to be a related resource 404.
>
> ```
> …
> 237 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 263ms (cache skip)
> 238 silly audit bulk request failed <h1>404 Not Found</h1>
> 239 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 1208ms (cache skip)
> 240 verbose audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
> …
> 241 silly audit error <h1>404 Not Found</h1>
> 242 timing auditReport:getReport Completed in 1622ms
> 243 silly audit report null
> 244 timing reify:audit Completed in 1624ms
> …
> 254 info run ffmpeg-static@5.0.0 install node_modules/ffmpeg-static node install.js
> 255 info run ffmpeg-static@5.0.0 install { code: 3221225786, signal: null }
> 256 timing reify:rollback:createSparse Completed in 494ms
> 257 timing reify:rollback:retireShallow Completed in 1ms
> 258 timing command:i Completed in 214520ms
> 259 verbose stack Error: command failed
> …
> 263 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "ffmpeg-static"
> …
> ```

I *assume* that it just failed because the audit (which is run automatically on `npm install` by default, and can be run manually via `npm audit`) failed with the npm mirror you're using (`registry.npmmirror.com`).

Can you check

- either if `ffmpeg-static` is installed (e.g. via `npm ls --depth 1 | grep ffmpeg-static`),
- or if it works `npm i ffmpeg-static --no-audit`?

**Comment by Danjuanlab** [comment]
> > […] it seems to be a related resource 404.
> > ```
> > …
> > 237 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 263ms (cache skip)
> > 238 silly audit bulk request failed <h1>404 Not Found</h1>
> > 239 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 1208ms (cache skip)
> > 240 verbose audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
> > …
> > 241 silly audit error <h1>404 Not Found</h1>
> > 242 timing auditReport:getReport Completed in 1622ms
> > 243 silly audit report null
> > 244 timing reify:audit Completed in 1624ms
> > …
> > 254 info run ffmpeg-static@5.0.0 install node_modules/ffmpeg-static node install.js
> > 255 info run ffmpeg-static@5.0.0 install { code: 3221225786, signal: null }
> > 256 timing reify:rollback:createSparse Completed in 494ms
> > 257 timing reify:rollback:retireShallow Completed in 1ms
> > 258 timing command:i Completed in 214520ms
> > 259 verbose stack Error: command failed
> > …
> > 263 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "ffmpeg-static"
> > …
> > ```
> 
> I _assume_ that it just failed because the audit (which is run automatically on `npm install` by default, and can be run manually via `npm audit`) failed with the npm mirror you're using (`registry.npmmirror.com`).
> 
> Can you check
> 
> * either if `ffmpeg-static` is installed (e.g. via `npm ls --depth 1 | grep ffmpeg-static`),
> * or if it works `npm i ffmpeg-static --no-audit`?

code 1
npm ERR! path C:\Users\zifan\Desktop\elsTools\electron-vite-vue-1.0.0\node_modules\ffmpeg-static
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Error: connect ETIMEDOUT 20.205.243.166:443
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
npm ERR!   errno: -4039,
npm ERR!   code: 'ETIMEDOUT',
npm ERR!   syscall: 'connect',
npm ERR!   address: '20.205.243.166',
npm ERR!   port: 443
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zifan\AppData\Local\npm-cache\_logs\2022-06-26T11_59_33_839Z-debug-0.log

**Comment by derhuerst** [comment]
> ```
> …
> npm ERR! Error: connect ETIMEDOUT 20.205.243.166:443
> …
> ```

Now we got to the actual problem: It fails to download the `ffmpeg` binary from the [`b5.0.0` GitHub release](https://github.com/eugeneware/ffmpeg-static/releases/tag/b5.0).

https://github.com/eugeneware/ffmpeg-static/blob/e546e43fe45fe1d4d2949a15c47bcca6e1eecbc1/install.js#L170

**The `ETIMEDOUT` error code suggests that there was a network error** when connecting to the server, possibly due to a) a flaky internet connection, b) some parental control or censorship software, or c) a random failure on GitHub's side (unlikely).

Do debug this error further, can you try downloading the `ffmpeg` binary using [`curl`](https://curl.se/windows/)? You need to pick the file matching your computer's architecture from the [`b5.0.0` GitHub release](https://github.com/eugeneware/ffmpeg-static/releases/tag/b5.0), e.g. `win32` for Windows, `x64` for 64-bit Intel/AMD:

```shell
curl 'https://github.com/eugeneware/ffmpeg-static/releases/download/b5.0/win32-x64.gz' -L -O -v
```

Please post the output here.

**Comment by Danjuanlab** [comment]
> ```shell
> curl 'https://github.com/eugeneware/ffmpeg-static/releases/download/b5.0/win32-x64.gz' -L -O -v
> ```

curl 'https://github.com/eugeneware/ffmpeg-static/releases/download/b5.0/win32-x64.gz'  -O test.zip
I can use this command to download ffmpeg, but the installation package still fails

```
PS C:\Users\zifan\Desktop\elsTools\electron-vite-vue-1.0.0> npm i ffmpeg-static --no-audit
npm ERR! code 3221225786
npm ERR! path C:\Users\zifan\Desktop\elsTools\electron-vite-vue-1.0.0\node_modules\ffmpeg-static
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Error creating cache: ENOENT: no such file or directory, mkdir 'C:\Users\zifan\AppData\Local\ffmpeg-static-nodejs\Cache'
npm ERR! ^C

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zifan\AppData\Local\npm-cache\_logs\2022-06-26T23_53_49_922Z-debug-0.log
^CTerminate batch job (Y/N)? y
PS C:\Users\zifan\Desktop\elsTools\electron-vite-vue-1.0.0> npm i ffmpeg-static --no-audit
Terminate batch job (Y/N)? n
PS C:\Users\zifan\Desktop\elsTools\electron-vite-vue-1.0.0> npm i ffmpeg-static --no-audit
npm ERR! code 3221225786
npm ERR! path C:\Users\zifan\Desktop\elsTools\electron-vite-vue-1.0.0\node_modules\ffmpeg-static
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Error creating cache: ENOENT: no such file or directory, mkdir 'C:\Users\zifan\AppData\Local\ffmpeg-static-nodejs\Cache'
npm ERR! ^C

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zifan\AppData\Local\npm-cache\_logs\2022-06-27T00_00_23_800Z-debug-0.log
```

**Comment by derhuerst** [comment]
This error is *yet another* different error, and indeed caused by `ffmpeg-static`'s `install.js` script:

It tries to create a directory `C:\Users\zifan\AppData\Local\ffmpeg-static-nodejs\Cache`, but `C:\Users\zifan\AppData\Local\ffmpeg-static-nodejs` doesn't even exist, so that fails.

I have pushed a fix for this, but not published it yet for technical reasons, so I'd ask you to manually create `C:\Users\zifan\AppData\Local\ffmpeg-static-nodejs`, and then try `npm i ffmpeg-static --no-audit` again and check if it works.

**Comment by Danjuanlab** [comment]
> npm i ffmpeg-static

It worked~

**Comment by derhuerst** [comment]
I will close this Issue because I have implemented a fix in `@derhuerst/http-basic`: https://github.com/derhuerst/http-basic/commit/2efef654f79d84a1f594fcad67686d4df8d68e95

This issue should still show up for Windows users (because [only on Windows the cache directory structure seems to be `<package-name>/Cache`](https://github.com/sindresorhus/env-paths/blob/f1729272888f45f6584e74dc4d0af3aecba9e7e8/index.js#L21-L33)) with Node.js <10 (because [from version 10, Node.js supports `recursive: true` with `mkdir`](https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_mkdir_path_options_callback)).
