### ISSUE TITLE
When can the `ffmpegPath` be `null`?

### ISSUE THREAD

**Issue by leafac** [eugeneware/ffmpeg-static#118]
[The type for `ffmpegPath` says that it can be `null`](https://github.com/eugeneware/ffmpeg-static/blob/a43ff37b26dac78a0512575ee0ad8911d3168dc8/types/index.d.ts).

When would this happen?

If, for example, `ffmpeg-static` can’t find a suitable binary, shouldn’t it fail to install in the first place?

And if that’s the case, are you interested in a pull request in which I remove the `null` from the type?

Thanks!

---

**Edit:** For the time being I’m doing the following awkward gymnastics:

```typescript
import assert from "node:assert/strict";
import maybeFFmpeg from "ffmpeg-static";
assert.equal(typeof maybeFFmpeg, "string");
const ffmpeg = maybeFFmpeg as unknown as string;

```

**Comment by derhuerst** [comment]
`ffmpegPath` can be `null` if the platform is not supported:

https://github.com/eugeneware/ffmpeg-static/blob/a43ff37b26dac78a0512575ee0ad8911d3168dc8/index.js#L31-L33

**Comment by derhuerst** [comment]
Please re-open if you have more questions related to this.
