### ISSUE TITLE
Permissions for static executables?

### ISSUE THREAD

**Issue by Gusterson** [eugeneware/ffmpeg-static#12]
Probably not your issue, but how do I ensure that the executables have the proper permissions when I distribute this? In my dev environment, I had to manually set the file to executable (linux, ubuntu). How do I remove this step?

**Comment by derhuerst** [comment]
I just tried with `ffmpeg-static@2.0.0`, and all binaries seem to be executable, as indicated by the `*`:

```
node_modules/ffmpeg-static/bin
├── darwin/
│   └── x64/
│       └── ffmpeg*
├── linux/
│   ├── ia32/
│   │   └── ffmpeg*
│   └── x64/
│       └── ffmpeg*
└── win32/
    ├── ia32/
    │   └── ffmpeg.exe*
    └── x64/
        └── ffmpeg.exe*

8 directories, 5 files
```

Please reopen if you still have a problem with it.
