### ISSUE TITLE
I can't find cutting stream function on ffmpeg-static

### ISSUE THREAD

**Issue by Fyphen1223** [eugeneware/ffmpeg-static#120]
I can't find cutting stream function on ffmpeg-static
I want to cut audio stream.

**Comment by Fyphen1223** [comment]
Sorry, I don't know how to mark this post as a question

**Comment by derhuerst** [comment]
This doesn't seem to be an issue with `ffmpeg-static` (which just downloads `ffmpeg` binaries), but with using [ffmpeg](https://ffmpeg.org) *itself*. This project merely provides ffmpeg binaries prebuilt by others. I cannot provide support for problems with ffmpeg here.

You can ask questions about how to use ffmpeg over at [SuperUser, where they have an `ffmpeg` tag](https://superuser.com/questions/tagged/ffmpeg). Please make sure to read & follow their instructions (e.g. provide the output of `ffmpeg -report` and your operating system). Good luck!
