### ISSUE TITLE
bug: Missing https protocol

### ISSUE THREAD

**Issue by threeFatCat** [eugeneware/ffmpeg-static#129]
### ffmpeg-static version

ffmpeg-static@4.3.6

### Node.js version

N/A

### operating system and/or environment

- using AWS Elastic Beanstalk
- Amazon Linux 2023 AMI

### What happened?

Installed the static build in AWS using .ebextensions
```
packages:
  yum:
    ImageMagick: []
    ImageMagick-devel: []
commands:
  01-wget:
    command: "wget -O /tmp/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
  02-mkdir:
    command: "if [ ! -d /opt/ffmpeg ] ; then mkdir -p /opt/ffmpeg; fi"
  03-tar:
    command: "tar xvf /tmp/ffmpeg.tar.xz -C /opt/ffmpeg --strip 1"
  04-ln:
    command: "if [[ ! -f /usr/bin/ffmpeg ]] ; then ln -s /opt/ffmpeg/ffmpeg /usr/bin/ffmpeg; fi"
  05-ln:
    command: "if [[ ! -f /usr/bin/ffprobe ]] ; then ln -s /opt/ffmpeg/ffprobe /usr/bin/ffprobe; fi"
  06-pecl:
    command: "if [ `pecl list | grep imagick` ] ; then pecl install -f imagick; fi"
```

Tried to run an ffmpeg command to concat images from s3 bucket. Concat by demuxing, and get the error that https protocol is not available. Running `ffmpeg -protocols`  shows `https` is not listed, while the build info here https://johnvansickle.com/ffmpeg/git-readme.txt says https is supported.

**Comment by derhuerst** [comment]
`ffmpeg-static` doesn't build its own binaries. Rather, we use the binary providers mentioned in the readme; Only they have influence over which features they include and if they work as intended.

Sorry.
