### ISSUE TITLE
bug:  Can you update npm packages to 6.0

### ISSUE THREAD

**Issue by RayCssjmt** [eugeneware/ffmpeg-static#132]
### ffmpeg-static version

@5.2.0

### Node.js version

v16

### operating system and/or environment

Window10  X64

### What happened?

 update npm packages to 6.0

**Comment by derhuerst** [comment]
Which ffmpeg version does `ffmpeg-static@5.2.0` download for you?

Can you post the output of the following commands?

```shell
node -p "require('ffmpeg-static/packagr.json').version"
node -p "require('ffmpeg-static')"
$(node -p "require('ffmpeg-static')") -help
```
