### ISSUE TITLE
How to get absolute path?

### ISSUE THREAD

**Issue by Maxou44** [eugeneware/ffmpeg-static#16]
With a electron app, when I require your module I get this object:

```
{
   path: "\bin\win32\x64\ffmpeg.exe"
}
```

The path is relative to the `node_modules` directory, how can I get the full absolute path?

**Comment by derhuerst** [comment]
This seems to be related to Electron. [This package merely appends to `__dirname`](https://github.com/eugeneware/ffmpeg-static/blob/a1ae1c18e135c13d6bb26ecd2d6f0b85c1bcc2c0/index.js#L16-L17).

**Comment by Maxou44** [comment]
Fixed by using `getAppPath()` and replace `app.asar` to fix the bundled path :)

```
import ffmpeg from 'ffmpeg-static';
import { remote } from 'electron';
import path from 'path';

const ffmpegPath = ((ffmpeg.path) ? path.join(remote.app.getAppPath().replace('app.asar', 'app.asar.unpacked'), 'node_modules/ffmpeg-static/', ffmpeg.path) : false);
```

Thanks for your awesome module :)

**Comment by derhuerst** [comment]
Note that you shouldn't assume `node_modules/ffmpeg-static`, as the npm package might be arbitrarily deeply nested inside `node_modules`. Use [`require.resolve()`](https://nodejs.org/api/modules.html#modules_require_resolve_request_options).

**Comment by Maxou44** [comment]
Thanks for the information :)
