### ISSUE TITLE
build script downloads the nightly Windows build

### ISSUE THREAD

**Issue by borestad** [eugeneware/ffmpeg-static#18]
http://ffmpeg.org/index.html#pr4.0

Time to upgrade? :-)

**Comment by derhuerst** [comment]
Done. `+ffmpeg-static@2.3.0`.

Someone should confirm that the Windows binary is the correct one.

**Comment by Inve1951** [comment]
CLI reports `ffmpeg version N-90920-ge07b1913fc`, the image itself does not have a [VERSIONINFO](https://msdn.com/aa381058).

**Comment by Inve1951** [comment]
```
ffmpeg version N-90920-ge07b1913fc Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 18.100 / 56. 18.100
libavcodec     58. 19.100 / 58. 19.100
libavformat    58. 13.100 / 58. 13.100
libavdevice    58.  4.100 / 58.  4.100
libavfilter     7. 21.100 /  7. 21.100
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
libpostproc    55.  2.100 / 55.  2.100
```

**Comment by derhuerst** [comment]
@Inve1951 What does the latest Windows binary from https://ffmpeg.zeranoe.com/builds/ report?

**Comment by Inve1951** [comment]
@derhuerst running the binary labeled 4.0/release on the site i get `ffmpeg version 4.0` in cli, the other one (20180508-293a6e8/nightly) gives `ffmpeg version N-91024-g293a6e8332`

**Comment by derhuerst** [comment]
Apparently the download script picks the nightly build. We should change it to pick the stable build.

https://github.com/eugeneware/ffmpeg-static/blob/d41d746e9632b89f74277139ecf18d0c6f0778ad/build/index.sh#L16

**Comment by derhuerst** [comment]
This should be fixed as of https://github.com/eugeneware/ffmpeg-static/commit/87515ed0a196f137b30e9d441122aab2eb701415.
