### ISSUE TITLE
Better version control

### ISSUE THREAD

**Issue by positlabs** [eugeneware/ffmpeg-static#2]
It would be nice to have more granular control over which version of ffmpeg is used. We could do this by tagging releases that include different versions of ffmpeg builds.

I'm not super familiar with publishing npm modules, but ideally, the version of the npm module would correspond with the version of ffmpeg builds. e.g. ffmpeg v2.8.3 == git release tag 2.8.3 == npm module  v2.8.3

We probably don't need 100% coverage, so maybe just including the most popular versions would be ok.

Thoughts?

**Comment by derhuerst** [comment]
Conceptually, this will be hard to achieve, for two reasons:

- What if this wrapper code has a bug? We will have to bump the version number to publish the fix.
- I'm not sure if ffmpeg strictly follows [SemVer](https://semver.org). Almost all of the tooling around Node follows SemVar.

It might sound disappointing, but I don't really see a way to make this happen.

**Comment by derhuerst** [comment]
Closing for now. Please reopen if you have new arguments/insights concerning this.
