### ISSUE TITLE
Update to FFmpeg 4.1

### ISSUE THREAD

**Issue by Maxou44** [eugeneware/ffmpeg-static#21]
FFmpeg 4.1 was release November, 6th, it could be interesting to update
https://www.ffmpeg.org/index.html#news

**Comment by Maxou44** [comment]
Thanks 😊

**Comment by derhuerst** [comment]
Thanks for you hint! Published as `ffmpeg-static@2.4.0`.

@borestad Can you confirm the Window binary is `4.1`?
