### ISSUE TITLE
Unsupported for android platform

### ISSUE THREAD

**Issue by lcron** [eugeneware/ffmpeg-static#28]
Android is based on Linux.
In theory, it should be used.

**Comment by MLXProjects** [comment]
Only the kernel and some libraries are based on Linux, most of it uses another runtime (bionic IIRC). 
While it may work, I doubt that as it needs alsa-lib (not used on Android, but tinyalsa)

**Comment by derhuerst** [comment]
Closing for now, as it seems unlikely to be solved.

If someone outlines at plan on how to get Android working though, I'll reopen.
