### ISSUE TITLE
example usage?

### ISSUE THREAD

**Issue by goatandsheep** [eugeneware/ffmpeg-static#32]
does this include an ffmpeg wrapper? How do I use this? Can you include an example in the readme?

**Comment by derhuerst** [comment]
In a44014d, I added [example code](example.js) that just converts to mp3, but obviously there are better use cases than writing an inflexible CLI wrapper, e.g. a media conversion API, parallelising `ffmpeg` calls, etc.

**Comment by goatandsheep** [comment]
Thank you!
