### ISSUE TITLE
Allow binary to be downloaded via proxy

### ISSUE THREAD

**Issue by jonah-dev** [eugeneware/ffmpeg-static#36]
It looks like the install script doesn't support downloading the binary via proxies. Would it be possible to utilize simple-get's proxy support to check for yarn/npm proxy environment variable?

**Comment by derhuerst** [comment]
PR welcome!

An [`Agent`](https://nodejs.org/docs/latest-v10.x/api/http.html#http_class_http_agent) needs to be passed into the `simple-get` call. I suggest to use [`https-proxy-agent`](https://github.com/TooTallNate/node-https-proxy-agent) or [`tunnel`](https://github.com/koichik/node-tunnel) for this. Parse the [`HTTPS_PROXY`](https://docs.npmjs.com/misc/config#https-proxy) & [`HTTP_PROXY`](https://docs.npmjs.com/misc/config#proxy) env vars using [`new URL()`](https://nodejs.org/docs/latest-v10.x/api/url.html#url_constructor_new_url_input_base).

**Comment by jonah-dev** [comment]
I'll see what I can do when I get some time to take a proper look at this.
