### ISSUE TITLE
support prefetched binaries via env var

### ISSUE THREAD

**Issue by muelli** [eugeneware/ffmpeg-static#37]
I am trying to package an app which app this library as a dependency.
I cannot download anything at install-time. Everything needs to be prefetched.
It seems as if this library is not capable of having the binary prefetched.
It would be nice if it could do that.
I know only little about the whole ecosystem, but [this](https://docs.npmjs.com/cli-commands/cache.html) could be relevant.

**Comment by derhuerst** [comment]
I'll be a bit pedantic here: A cache technically is a different thing, as it is usually considered to be ephemeral; The software does not *depend* on the cache to be populated in order to function correctly. For example, the cache used by npm can be cleared by the user or the system at any time, but npm is still supposed to function correctly.

Let's add support for an environment variable specifying the location of the `ffmpeg` binaries (e.g. `FFMPEG_STATIC_DIR`). `ffmpeg-static`'s `install` script would download the `ffmpeg` binary to this directory, and `index.js` would expect the binary to be in there.

**Comment by muelli** [comment]
What I meant was to download the file to the cache folder and install it from there rather than installing it from the Internet directly. So at installation time you don't download straight to the target but you check the cache first and if the file is there, you copy it over to the target path. Otherwise you download it (into the cache folder). This has several advantages. One of them is my use case: packaging apps for any serious environment. The other is that you are more resource friendly when installing on the same machine multiple times.

**Comment by derhuerst** [comment]
You‘ve explained a different use case above. There are two different use cases:

- support prefetched binaries, for packaged/bundled apps
- optimizing multiple installs by caching the binaries

**Comment by derhuerst** [comment]
> I cannot download anything at install-time. Everything needs to be prefetched.

This should work now:

1. Export the env var `FFMPEG_BIN` with the path of a directory *outside* `node_modules`, e.g. `export FFMPEG_BIN='/home/muelli/my-app/ffmpeg'`.
2. `npm install ffmpeg-static@4.1.0`.
3. Check if the `ffmpeg` binary has been downloaded to the specific directory.
4. Put this directory/binary in your app package, and make sure `FFMPEG_BIN` is set when the user runs the app.

**Comment by muelli** [comment]
I can't make it work.


> * Export the env var `FFMPEG_BIN` with the path of a directory _outside_ `node_modules`, e.g. `export FFMPEG_BIN='/home/muelli/my-app/ffmpeg'`.

At install-time, I suppose. Done [here](https://github.com/flathub/no.mifi.losslesscut/blob/fee915b74401f3e5a0542e4714570bf698df2cdd/no.mifi.losslesscut.yaml#L54).

> 
> * `npm install ffmpeg-static@4.1.0`.
> 

That's the [version](https://github.com/flathub/no.mifi.losslesscut/blob/fee915b74401f3e5a0542e4714570bf698df2cdd/generated-sources.0.json#L4734) that is used.

> * Check if the `ffmpeg` binary has been downloaded to the specific directory.

Checked [here](https://github.com/flathub/no.mifi.losslesscut/blob/fee915b74401f3e5a0542e4714570bf698df2cdd/no.mifi.losslesscut.yaml#L81).

> 
> * Put this directory/binary in your app package, and make sure `FFMPEG_BIN` is set when the user runs the app.

[Done](https://github.com/flathub/no.mifi.losslesscut/blob/fee915b74401f3e5a0542e4714570bf698df2cdd/no.mifi.losslesscut.yaml#L136), but I don't get to that stage, because installation fails:

```
[4/4] Building fresh packages...
[1/7] ⠐ ffmpeg-static
[2/7] ⠐ core-js
[3/7] ⠐ ejs
[6/7] ⠐ core-js
error /run/build/losless-cut/node_modules/ffmpeg-static: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /run/build/losless-cut/node_modules/ffmpeg-static
```

Here's the [build log](https://flathub.org/builds/#/builders/10/builds/2144).

**Comment by derhuerst** [comment]
Sorry, I made a trivial mistake, which I have fixed in 32066b8/`ffmpeg-static@4.1.1`. Please try again with this version.

I haven't read all of your linked code, but keep in mind that `FFMPEG_BIN` points to the `ffmpeg` binary *itself*, not to the directory which it is in.

That aside, I don't really understand your setup yet. Do you even use `ffmpeg-static` from Node.js code somewhere? That's what it is intended for.

**Comment by muelli** [comment]
I still can't make it work. It still wants to connect to the Internet.

```
[4/4] Building fresh packages...
[1/7] ⠠ ffmpeg-static
[6/7] ⠠ electron
[-/7] ⠠ waiting...
[-/7] ⠠ waiting...
error /run/build/losless-cut/node_modules/ffmpeg-static: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /run/build/losless-cut/node_modules/ffmpeg-static
Output:
{ Error: getaddrinfo EAI_AGAIN github.com github.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'github.com',

```

Notice, how it the variable correctly identifies the path of the ffmpeg-static binary just before yarn is called:
```
$ /bin/sh -c 'ls -la $(echo ${FFMPEG_BIN})'
-rwxr-xr-x 1 muelli muelli 75282080 Mar 31 08:18 /app/lib/ffmpeg/bin/ffmpeg-static
```

This is now using [ffmpeg-static 4.2.0](https://github.com/flathub/no.mifi.losslesscut/blob/e456c419c5d492f64979fbe2d46ec86db0e88299/generated-sources.0.json#L5000). The variable is [set here](https://github.com/flathub/no.mifi.losslesscut/blob/e456c419c5d492f64979fbe2d46ec86db0e88299/no.mifi.losslesscut.yaml#L54). The binary is downloaded [here](https://github.com/flathub/no.mifi.losslesscut/blob/e456c419c5d492f64979fbe2d46ec86db0e88299/no.mifi.losslesscut.yaml#L128). See the [build log](https://flathub.org/builds/#/builders/35/builds/2285) for more details. I'm happy to walk you through the things that are still unclear.

The package is used by lossless-cut which I am trying to package for distribution. But a requirement is to identify all files that will be distributed at build-time.

**Comment by derhuerst** [comment]
> I still can't make it work. It still wants to connect to the Internet. [...]

Sorry, thanks for being patient with me!
 
> This is now using [ffmpeg-static 4.2.0](https://github.com/flathub/no.mifi.losslesscut/blob/e456c419c5d492f64979fbe2d46ec86db0e88299/generated-sources.0.json#L5000). The variable is [set here](https://github.com/flathub/no.mifi.losslesscut/blob/e456c419c5d492f64979fbe2d46ec86db0e88299/no.mifi.losslesscut.yaml#L54). The binary is downloaded [here](https://github.com/flathub/no.mifi.losslesscut/blob/e456c419c5d492f64979fbe2d46ec86db0e88299/no.mifi.losslesscut.yaml#L128). See the [build log](https://flathub.org/builds/#/builders/35/builds/2285) for more details. I'm happy to walk you through the things that are still unclear.

Thanks for the amazing bug report!

---

I've published another fix as `ffmpeg-static@4.2.1`, please try it again. This time, I've tried "from the outside", not within the repo.

**Comment by derhuerst** [comment]
The desired behaviour:

If `FFMPEG_BIN` is set, the install script will check if there's a file this location. If there is, it will exit, trusting that has put a valid `ffmpeg` binary there. If it's `stat $FFMPEG_BIN` throws `ENOENT`, it will download the binary to this location.

Let me know if this doesn't work for you. Keep in mind that `FFMPEG_BIN` needs to be set *both* during install, and during runtime.

**Comment by muelli** [comment]
it doesn't work as expected.
The variable is set both at install-time and at runtime.
Yet, it exposes the behaviour mentioned above.

**Comment by derhuerst** [comment]
Sorry that it is broken for you!

I'm having trouble reproducing this. Did you set `$FFMPEG_BIN` to an absolute path?

This works for me:

```shell
cd ~/web/ffmpeg-static
git checkout v4.2.1
npm pack # produces ffmpeg-static-4.2.1.tgz

cd ~/playground
mkdir ffmpeg-static-test
cd ffmpeg-static-test
npm init --yes

export FFMPEG_BIN='/Users/j/Downloads/ffmpeg-foo'
touch "$FFMPEG_BIN"
npm install ~/web/ffmpeg-static/ffmpeg-static-4.2.1.tgz
# > ffmpeg-static@4.2.1 install /Users/j/playground/ffmpeg-static-test/node_modules/ffmpeg-static
# > node install.js
#
# ffmpeg is installed already.
# npm notice created a lockfile as package-lock.json. You should commit this file.
# npm WARN ffmpeg-static-test@1.0.0 No description
# npm WARN ffmpeg-static-test@1.0.0 No repository field.
#
# + ffmpeg-static@4.2.1
# added 23 packages from 52 contributors in 1.904s
# found 0 vulnerabilities
```

**Comment by muelli** [comment]
you're showing how to install the package, right? But you're not showing that it will indeed try to execute that file at runtime. And that is, what is failing for me. Installation works. But execution doesn't.

**Comment by muelli** [comment]
ah. wait. you're not claiming to execute ffmpeg at all.
Are you "only" providing the binary and the caller has to obtain the path and execute it themself?
Then I need to look into lossless-cut. Maybe there, the path to ffmpeg is hardcoded.

**Comment by derhuerst** [comment]
> ah. wait. you're not claiming to execute ffmpeg at all.

Yes! I should never make network requests *at runtime* though!

> Are you "only" providing the binary and the caller has to obtain the path and execute it themself?

Exactly. How can we improve the readme to make this more clear?

**Comment by muelli** [comment]
> ah. wait. you're not claiming to execute ffmpeg at all.

yep, the bug is here: https://github.com/mifi/lossless-cut/blob/9b3af1a995ff54018169846325abe1e3ca0ece6e/src/ffmpeg.js#L37
It seems it expects this module expect to provide the binary in a certain path rather than resolve the path. I will file a bug.  Sorry for the noise.

That said, I think that depending on the variable at runtime is a bit clunky, as the same functionality could be provided without requiring the variable to be set later. And this kind of flexibility is what I believe will cause surprises and confused users down the road.

Anyway, thanks for being patient and professional <3
I think we can close here and I will follow-up with lossless-cut.

**Comment by derhuerst** [comment]
> That said, I think that depending on the variable at runtime is a bit clunky, as the same functionality could be provided without requiring the variable to be set later. And this kind of flexibility is what I believe will cause surprises and confused users down the road.

Okay, so far I have considered it a feature. Still, with `FFMPEG_BIN` being set, this package is nothing more than `module.exports = process.env.FFMPEG_BIN`. 😬

> Anyway, thanks for being patient and professional <3

🙌
