### ISSUE TITLE
ffprobe and pull requests

### ISSUE THREAD

**Issue by FallingSnow** [eugeneware/ffmpeg-static#4]
Can ffprobe and ffplay be added to the package? Also do you accept pull requests for updates?

**Comment by eugeneware** [comment]
Hi @FallingSnow, there's already another package called [ffprobe-static](https://github.com/joshwnj/ffprobe-static) for `ffprobe`. The size of the binaries is quite large, which causes issues with use on sites like heroku. Probably better to live in another package.

And yes, PR's are absolutely accepted!

**Comment by FallingSnow** [comment]
Awesome! All the answers I was hoping for!

**Comment by robertmain** [comment]
@eugeneware this should really be re-opened since the package you referenced provides ffprobe for OSX only. That's not really a solution imho.
