### ISSUE TITLE
Failed to download the ffmpeg README and LICENSE

### ISSUE THREAD

**Issue by mxschmitt** [eugeneware/ffmpeg-static#42]
During the installation these two warnings popup, nothing critical but would be awesome to either hide or fix these.

```
> ffmpeg-static@4.1.0 install /backend/node_modules/ffmpeg-static
> node install.js

Error creating cache: ENOENT: no such file or directory, mkdir '/root/.cache/ffmpeg-static-nodejs'

Failed to download the ffmpeg README.
Failed to download the ffmpeg LICENSE.
```

version: 4.1.0

**Comment by derhuerst** [comment]
When I did [the last binaries release](https://github.com/eugeneware/ffmpeg-static/releases/tag/b4.2.2), the CI wasn't configured to upload `README` & `LICENSE` files as well. This will be done with the next binaries release.
