### ISSUE TITLE
Update to FFmpeg 4.3

### ISSUE THREAD

**Issue by Maxou44** [eugeneware/ffmpeg-static#51]
Hello,

FFmpeg released 4.3.0 two days ago, any plan to update this package?

https://www.ffmpeg.org/download.html

Have a great day,
Maxime

**Comment by derhuerst** [comment]
Yes, I do plan to upgrade.

I‘m waiting for the binary providers to publish 4.3 binaries. Would be cool if someone could post here as soon as all three providers (see readme) have binaries.

**Comment by Maxou44** [comment]
Windows builds were released by Zeranoe 😏

**Comment by derhuerst** [comment]
Fixed as of 7d330bd, published as `ffmpeg-static@4.2.5`. :shipit:
