### ISSUE TITLE
Add GL Transitions to FFMPEG Build?

### ISSUE THREAD

**Issue by tommyc38** [eugeneware/ffmpeg-static#57]
Any chance you would consider compiling ffmpeg with the gl-transitions filter?  [See here](https://github.com/transitive-bullshit/ffmpeg-gl-transition)

**Comment by derhuerst** [comment]
This library actually just downloads/distributes ffmpeg binaries [prebuilt by other people](https://github.com/eugeneware/ffmpeg-static/blob/2fce51e2d97c880befb12c5b1b481dbac457569e/README.md), so this is out of scope, sorry. You can try getting in touch with the maintainer(s) of the respective binary(s).
