### ISSUE TITLE
FFMPEG 4.3 Audio Choppiness when Streaming or Recording WebCam

### ISSUE THREAD

**Issue by FullstackJack** [eugeneware/ffmpeg-static#58]
When using FFMPEG 4.3 with AVFoundation to livestream from a webcam over RTMP, the audio ends up playing back choppy. What does that sounds like? Imagine every second someone unplugging your surround sound speakers and then plugging them back in very quickly while you're trying to watch a movie almost like a heart beat. After about a day of searching around the net and trying different parameters, I decided to give my brew version of FFMPEG a try with the same settings. Low and behold, the audio didn't sound choppy! What was different? Version 4.1 installed on my system, that's what. Since there doesn't seem to be a 4.1 of ffmpeg-static, I tried the next best thing: 4.2.2. This actually solved my problem, even though someone on the issue tracker mentions that it didn't work for them in 4.2.2.

https://trac.ffmpeg.org/ticket/4513

It looks like there was a patch in older version of FFMPEG that never got applied to newest version of FFMPEG.  I don't know how that didn't get merged (they use archaic source control SVN).  Since 4.3 seems to be the highest version, the best plan is to rollback your version to 4.2.2. I do realize the ffmpeg-static library maintainers probably won't rollback 4.3 to 4.2.2, but for anyone coming along, hopefully this information is helpful.

Here is my test command:

`node_modules/ffmpeg-static/ffmpeg -f avfoundation -framerate 30 -video_size 1280x720 -i "0:0" -vcodec libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -thread_type slice -slices 1 -r 30 -g 60 -b:v 2.5M -minrate:v 900k -bufsize:v 5M -maxrate:v 2.5M -acodec aac -b:a 128k -ac 2 -ar 48000 -af aresample=async=1 -bufsize 5000k -f flv rtmp://myserver.example.com:1935/live/teststream`

**Comment by derhuerst** [comment]
> [...] I decided to give my brew version of FFMPEG a try with the same settings. Low and behold, the audio didn't sound choppy! What was different? Version 4.1 installed on my system, that's what. Since there doesn't seem to be a 4.1 of ffmpeg-static, I tried the next best thing: 4.2.2. This actually solved my problem, even though someone on the issue tracker mentions that it didn't work for them in 4.2.2.

I don't know if this is an issue specific to ffmpeg 4.3, or if it is due to the [binary that `ffmpeg-static` downloads](https://github.com/eugeneware/ffmpeg-static/tree/18acfdfc0b852863d46a8cbe3873a2c9e3fc792e#sources-of-the-binaries).

> I do realize the ffmpeg-static library maintainers probably won't rollback 4.3 to 4.2.2 [...].

Correct, I would really really like to avoid rolling back to *any* older/specific ffmpeg version. For any ffmpeg release, there might be >0 unfixed bugs, so making a deliberate decision which release to pick *for `ffmpeg-static`* seems like a rabbit hole I don't want to go down into.

Let's hope that your issues will be fixed soon!

**Comment by derhuerst** [comment]
I'm going to close this Issue, because I cannot fix it here in `ffmpeg-static` and I don't want to roll back. I hope you understand this.
