### ISSUE TITLE
ffmpeg.zeranoe.com is closing

### ISSUE THREAD

**Issue by advaith1** [eugeneware/ffmpeg-static#60]
[ffmpeg.zeranoe.com](https://ffmpeg.zeranoe.com/builds/), which ffmpeg-static uses for Windows builds, is closing ([tweet](https://twitter.com/Zeranoe/status/1300596971934224385), banner on site)

**Comment by Maxou44** [comment]
Any alternatives ? Maybe we can create another repository to self-build from source ffmpeg using Github actions ?

**Comment by derhuerst** [comment]
[Seems like someone's willing to continue maintaining Mac & Windows builds.](https://twitter.com/satishsampath/status/1303573907060871168) Let's see.

**Comment by TheLastZombie** [comment]
Also: https://github.com/ScoopInstaller/Main/issues/1379#issuecomment-690844485

**Comment by advaith1** [comment]
[ShareX](https://getsharex.com) is now putting builds on [ShareX/FFmpeg/releases](https://github.com/ShareX/FFmpeg/releases)

**Comment by derhuerst** [comment]
Let‘s use the ShareX binaries then. PR welcome!

**Comment by maceocis** [comment]
Hi FFMPEG experts,
I created a Blog where I will put exiting source code and projects arround FFMPEG and video in general. There is already an FFMPEG SDL video player.
If you are interested, please check my blog:
https://videoprocessingexpert.wordpress.com/
