### ISSUE TITLE
Multiple EACCESS errors at install.js

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [eugeneware/ffmpeg-static#63]
I recently updated the ffmpeg-static dependency in one of my projects, but I am now getting this while installing (on root user):
```
Error reading from cache: EACCES: permission denied, open '/root/.cache/ffmpeg-static-nodejs/718960d5a79e5a6263f198570f2db949106e38fa7c2bdb1e52fd47f7a6c6081d6d5157fe5e63a4d65baba222daf54c8f5be5958c2b34e4822d599b3b13231fb0.json'
Error reading from cache: EACCES: permission denied, open '/root/.cache/ffmpeg-static-nodejs/dd451afd5a3c5c3b643274afb5337daaae30d04dc25b2974538bb847aae4d3782cf97cb4b048ff7eb1b11d8ca1b0acbe86578291b244142e9fa5a8d280c698dd.json'
Error creating cache: EACCES: permission denied, mkdir '/root/.cache/ffmpeg-static-nodejs'
[Error: EACCES: permission denied, open '/usr/lib/node_modules/yt_mp3_downloader/node_modules/ffmpeg-static/ffmpeg'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/node_modules/yt_mp3_downloader/node_modules/ffmpeg-static/ffmpeg'
}
```
This only happens on my server and with the latest ffmpeg. I am not sure what's going on.
Directly running `npm install ffmpeg-static -g` returns the same.

**Comment by derhuerst** [comment]
This might be the same as #64.

In the same environment you're installing this in, could you give me the output of `ls -l /root/.cache` and `ls -l /root/.cache/ffmpeg-static-nodejs`?

**Comment by LevitatingBusinessMan** [comment]
```
god@spackjarrow: ~# ls -al /root/.cache
total 16
drwxr-xr-x 4 root root 4096 Aug 21 20:08 .
drwx------ 9 root root 4096 Sep 15 19:47 ..
drwxr-xr-x 2 root root 4096 Aug 23 22:55 fff
drwxr-xr-x 3 root root 4096 Aug 21 20:09 jellyfin
```
```
god@spackjarrow: ~# ls -l /root/.cache/ffmpeg-static-nodejs
ls: cannot access '/root/.cache/ffmpeg-static-nodejs': No such file or directory
```

**Comment by derhuerst** [comment]
`/root/.cache` exists, so it seems like your problem is different from #64.

Could it be that the `node` process is not allowed to create a directory in `/root/.cache`? Can you try running `mkdir /root/.cache/ffmpeg-static-nodejs`, as the same user as `node`, with the same permissions (and if it's inside a Docker container, also in there)?

**Comment by LevitatingBusinessMan** [comment]
I ran the node interpreter (as root) and made it run `exec("mkdir /root/.cache/ffmpeg-static-nodejs")` which ran fine.

**Comment by derhuerst** [comment]
So did you run the `npm install` process as root as well?

**Comment by LevitatingBusinessMan** [comment]
Yes

**Comment by derhuerst** [comment]
Interesting. Can you check if the issue is gone now?

**Comment by LevitatingBusinessMan** [comment]
@derhuerst sorry for the extremely late reply, no the issue persists.
```
Error reading from cache: EACCES: permission denied, open '/root/.cache/ffmpeg-static-nodejs/718960d5a79e5a6263f198570f2db949106e38fa7c2bdb1e52fd47f7a6c6081d6d5157fe5e63a4d65baba222daf54c8f5be5958c2b34e4822d599b3b13231fb0.json'
Error reading from cache: EACCES: permission denied, open '/root/.cache/ffmpeg-static-nodejs/dd451afd5a3c5c3b643274afb5337daaae30d04dc25b2974538bb847aae4d3782cf97cb4b048ff7eb1b11d8ca1b0acbe86578291b244142e9fa5a8d280c698dd.json'
Error creating cache: EACCES: permission denied, mkdir '/root/.cache/ffmpeg-static-nodejs'
```
Honestly I have no clue why it's doing this

**Comment by derhuerst** [comment]
It's trying to cache the ffmpeg binary that will download.

I cannot reproduce the issue though, so I can't really help you. Just to reiterate: Please make sure that the `node` process has write access to the cache location (`/root/.cache` in your case).
