### ISSUE TITLE
Filter missing 

### ISSUE THREAD

**Issue by aalasolutions** [eugeneware/ffmpeg-static#66]
I have screen recorded a video where I got lot of black frames in start and end via node + ffmpeg-static 

To remove the black frames I used the following command

```
ffmpeg -i input.mp4 -vf mpdecimate,setpts=N/FRAME_RATE/TB output.mp4
```

If I use this with a version installed with apt-get this command works fine, but when I use it with ffmpeg-static's ffmpeg version i got the following error. 

```
Unable to find a suitable output format for 'mpdecimate,setpts=N/FRAME_RATE/TB' mpdecimate,setpts=N/FRAME_RATE/TB: Invalid argumen
```

**Comment by derhuerst** [comment]
I assume you have solved the issue? Can you elaborate, so that others can learn from this as well?

**Comment by aalasolutions** [comment]
No..

well, i was having typo in the arguments... it is working fine for me. thanks
