### ISSUE TITLE
Error: ffmpeg stream: write EPIPE

### ISSUE THREAD

**Issue by Gamer85x** [eugeneware/ffmpeg-static#67]
Hello, I have a problem in my code.
If I execute command on Discord `!play` my bot join to the voice channel and in console send to me an error.
There is my [code and an error](https://hastebin.com/botafisiru.typescript).
Help me. pls

**Comment by derhuerst** [comment]
You code uses [`ytdl-code`](https://github.com/fent/node-ytdl-core), which is not related to `ffmpeg-static`, so I can't help you with questions related to that.

In general, `EPIPE` is a common error when you write to a pipe in Node.js that has already been closed. Probably there are 2 processes being piped together, and the 1st tries to write after the 2nd has already failed.
