### ISSUE TITLE
Install failing on Ubuntu due to install.js

### ISSUE THREAD

**Issue by stavoxnetworks** [eugeneware/ffmpeg-static#68]
I have tried to perform on install this morning on Ubuntu 18.04. 

"npm install ffmpeg-static" fails citing issues within the install.js. 

![node install js](https://user-images.githubusercontent.com/27533789/98977794-054e6080-24e7-11eb-8acf-094aac22cb7a.png)

**Comment by stavoxnetworks** [comment]
It seems to be an issue around the dependency installs. I had to install http-basic manually and re-run the npm installer. It now complains that the URL variable is not defined.

![Screenshot from 2020-11-12 14-21-40](https://user-images.githubusercontent.com/27533789/98986237-a2fb5d00-24f2-11eb-98dc-9ba59ad2b5ec.png)

**Comment by derhuerst** [comment]
Which Node.js version are you trying to install `ffmpeg-static` with? Please make you're using at least 10, using `node -v`.

**Comment by derhuerst** [comment]
Ah, I can see from the logs that you're using Node.js v8.10.0, which is not supported.

**Comment by stavoxnetworks** [comment]
That did solve the issue. I had an older version of node installed at /usr/bin even though I had a v15 installation as well. SOrry to bother you guys.
