### ISSUE TITLE
Add builds with libfdk_aac, and builds for each Linux platform with access to pulseaudio

### ISSUE THREAD

**Issue by voxsoftware** [eugeneware/ffmpeg-static#7]
Add builds with libfdk, and builds for each Linux platform with access to pulse

**Comment by derhuerst** [comment]
Let me know if I misunderstood your proposal!

This library is merely a "container" for the [prebuilt binaries provided by notable download servers](https://github.com/eugeneware/ffmpeg-static/blob/0b1bcafd58db7fb586a804eadb004cf897eac400/build/index.sh#L13-L43). Its scope is *not* to custom-build ffmpeg.

**Comment by derhuerst** [comment]
Closing. Please reopen if you feel that I haven't answered your question.
