### ISSUE TITLE
Gatekeeper on macOS 11 Big Sur causes SIGKILL

### ISSUE THREAD

**Issue by livc** [eugeneware/ffmpeg-static#71]
```
$ node
Welcome to Node.js v12.14.1.
Type ".help" for more information.
>
> var ffmpeg = require('fluent-ffmpeg');
undefined
> ffmpeg.setFfmpegPath(require('ffmpeg-static'))
undefined
> var proc = ffmpeg().input('public/SHTUIntro/skd.mp3')
undefined
> proc.output("output.mp3").run()
undefined
> Thrown:
[Error: ffmpeg was killed with signal SIGKILL] {
  domainEmitter: FfmpegCommand {
```

Intel CPU Macbook Pro. 

But the script works on macOS Catalina.

**Comment by derhuerst** [comment]
Can you either a) run ffmpeg from the command line (shown below), or b) make the error output visible by using `.on('error', console.error)`?

```shell
(node -p 'require("ffmpeg-static")') -i public/SHTUIntro/skd.mp3 -o output.mp3
```

**Comment by livc** [comment]
@derhuerst Hi
```
$ (node -p 'require("ffmpeg-static")') -i public/SHTUIntro/skd.mp3 -o output.mp3
zsh: parse error near `-i'
```
Is it correct command?

**Comment by derhuerst** [comment]
The `$` and the `(` need to be together. We're trying to execute whatever `node -p 'require("ffmpeg-static")'` prints.

**Comment by livc** [comment]
It works.
```
$ node -p 'require("ffmpeg-static")'
/Users/xxx/Desktop/xxx/node_modules/ffmpeg-static/ffmpeg
```

**Comment by derhuerst** [comment]
Sorry, GitHub automatically stripped the `$` from my code snippet above. 🙄 Can you try running it again with the `$`?

```shell
$(node -p 'require("ffmpeg-static")') -i public/SHTUIntro/skd.mp3 -o output.mp3
```

**Comment by livc** [comment]
```
$ $(node -p 'require("ffmpeg-static")') -i public/SHTUIntro/skd.mp3 -o output.mp3
[1]    20975 killed     $(node -p 'require("ffmpeg-static")') -i public/SHTUIntro/skd.mp3 -o
```

**Comment by derhuerst** [comment]
Interesting, because I get this:

```
ffmpeg version 4.3.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Unrecognized option 'o'.
Error splitting the argument list: Option not found
```

What happens if you run `$(node -p 'require("ffmpeg-static")') -version`?

**Comment by livc** [comment]
```
$ $(node -p 'require("ffmpeg-static")') -version
[1]    21082 killed     $(node -p 'require("ffmpeg-static")') -version
```

**Comment by derhuerst** [comment]
Ok, yet another attempt to figure this out: `file $(node -p 'require("ffmpeg-static")')`.

**Comment by livc** [comment]
```
$ file $(node -p 'require("ffmpeg-static")')
/Users/xxx/Desktop/xxx/node_modules/ffmpeg-static/ffmpeg: Mach-O 64-bit executable x86_64
```

**Comment by derhuerst** [comment]
Since the issue appears even when running the `ffmpeg` binary from zsh, I'm pretty sure that `ffmpeg-static` & `fluent-ffmpeg` are not the cause. There must be something on your system that prevents `ffmpeg` from running successfully, e.g. lack of available memory, Gatekeeper killing it, or some antivirus system, I'm really not sure.

Please verify that you can download & run a manually download an [ffmpeg binary](https://evermeet.cx/pub/ffmpeg/).

**Comment by livc** [comment]
Thanks.

The first time ffmpeg was killed but warn me to allow unidentified developers on macOS Security & Privacy setting page. After allowing that it works!

```
$ ~/Downloads/ffmpeg
[1]    25250 killed     ~/Downloads/ffmpeg

$ ~/Downloads/ffmpeg
ffmpeg version 4.3.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
```

But I still don't know how to allow the ffmpeg in my node_modules directory?

**Comment by derhuerst** [comment]
> But I still don't know how to allow the ffmpeg in my node_modules directory?

Does the "Security & Privary preference pane" in System Preferences show something after trying to run it? If that turns out to actually be the cause, we should document it.

**Comment by livc** [comment]
> Does the "Security & Privary preference pane" in System Preferences show something after trying to run it? 

No.

**Comment by livc** [comment]
@derhuerst Hi, any suggestions? What should I do?

**Comment by derhuerst** [comment]
I don‘t have suggestions, as I don‘t have an idea what‘s going on.

You could download the `ffmpeg` binary manually from the releases page and check if you can run it from the command line.

**Comment by livc** [comment]
Same as the binary file downloaded from  https://evermeet.cx/pub/ffmpeg/ : 

First warning:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/11692045/102711266-39d9e700-42f3-11eb-88db-396ec38e009d.png">

After allowing it works:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/11692045/102711263-347c9c80-42f3-11eb-8981-b85d69751033.png">

But there are no warning pop-ups when I run ffmpeg from node_modules directory.

**Comment by livc** [comment]
I use the binary file downloaded from [the release page](https://github.com/eugeneware/ffmpeg-static/releases/tag/b4.3.1) to replace that in my `node_modules/ffmpeg-static/ffmpeg` and it works.

**Comment by derhuerst** [comment]
Okay, at least we‘re narrowed the issue down to [Gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)) by now.

Can you try another thing? (Or @juliuste might do it.)

1. Delete the current installation of `ffmpeg-static` by running `npm rm ffmpeg-static` & `rm -r ~/Library/Caches/ffmpeg-static-nodejs`.
2. Install `ffmpeg-static`.
3. Try to allow the binary with Gatekeeper: `sudo spctl -add $(node -p 'require("ffmpeg-static")')`
4. Try to use the binary.

**Comment by livc** [comment]
Hi, after step 2, I found the ffmpeg is executable and not killed. I don't know if it is because I have agreed in 

> After allowing it works:

**Comment by derhuerst** [comment]
> Hi, after step 2, I found the ffmpeg is executable and not killed. I don't know if it is because I have agreed in

If marking binaries as allowed works by their hash/digest, then probably.

You can manually install `ffmpeg-static@4.2.6`, which will download the `4.3` ffmpeg binary, instead of the `4.3.1` one. Then, the Gatekeeper problem should re-appear.

**Comment by livc** [comment]
Hi, I try with `ffmpeg-static@4.2.6`, there is still no Gatekeeper problem.

**Comment by derhuerst** [comment]
Does this issue appear with `ffmpeg-static@4.4`?

**Comment by derhuerst** [comment]
Please re-open once you (or someone else) have checked if [my proposed steps](https://github.com/eugeneware/ffmpeg-static/issues/71#issuecomment-748615683) work with an ffmpeg binary you haven't installed before, e.g. `ffmpeg-static@4.4`.
