### ISSUE TITLE
spawn \ffmpeg.exe ENOENT with nw.js (create-nw-react-app)

### ISSUE THREAD

**Issue by Timber1900** [eugeneware/ffmpeg-static#74]
I'm using ffmpeg-static on a React/nw.js project and instead of `const ffmpeg = require('ffmpeg-static')` or `import ffmpeg from 'ffmpeg-static'` giving me a path to the exe it just returns `\ffmpeg.exe`, I've reinstalled the module, deleted node_modules and nothing worked.

I dont think nw.js is the problem since another nw.js project of mine uses ffmpeg-static and it works fine.

- Error output
```
node:internal/child_process:276 Uncaught (in promise) Error: spawn \ffmpeg.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:276:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

**Comment by Timber1900** [comment]
- No I didn't set the `FFMPEG_BIN` environment variable, honestly I don't even know what it its or what it does.
- The only diffrence between both projects is that one is js/vanilla html and the other, the broken one, is ts/react, if it helps it was created using `create-nw-react-app` and then manually converted to typescript

**Comment by Timber1900** [comment]
- Found the issue, `ffmpeg-static` doesn't have types so typescript recommended declaring ffmpeg-static, this seems to have broken it somehow and removing it fixed the issue, and requiring it returns the correct path, feel free to close the issue.
- Thanks for the help

**Comment by derhuerst** [comment]
> The only diffrence between both projects is that one is js/vanilla html and the other, the broken one, is ts/react, if it helps it was created using `create-nw-react-app` and then manually converted to typescript

Well, the only reason I can think of right now is that the bundler used by `create-nw-react-app`-created apps does something weird with `ffmpeg-static`.

During installation `ffmpeg-static` downloads the appropriate `ffmpeg` binary and stores it inside its directory. When `require`ing or `import`ing `ffmpeg-static`, it returns the path to that binary. It could be that some build step in `create-nw-react-app` strips this binary from the generated app.

**Comment by derhuerst** [comment]
> `ffmpeg-static` doesn't have types so typescript recommended declaring ffmpeg-static, this seems to have broken it somehow and removing it fixed the issue [...].

Great to hear that!

How did you "declare" it? Please explain your solution, so that others can benefit from it.

**Comment by Timber1900** [comment]
I have to remove my statement it is not fixed, inputing `const ffmpeg = require('ffmpeg-static');` on the dev tools gives the correct path but not on the .ts file, I was declaring it as a module on a  .d.ts file by putting `declare module 'ffmpeg-static'` there

**Comment by Timber1900** [comment]
# Update
- I think the error has something to do with require/import, I looked at the function on devtools and found that nwjs messed with it, have the 'real' require be nw.require, substituting this on my code yielded the expexted result, I still dont fully understant why this would happen but it is working now.
![image](https://user-images.githubusercontent.com/9287896/106924914-7af15380-6707-11eb-965e-f7b6599ed921.png)

**Comment by derhuerst** [comment]
> [...] inputing `const ffmpeg = require('ffmpeg-static');` on the dev tools gives the correct path but not on the .ts file, I was declaring it as a module on a .d.ts file by putting `declare module 'ffmpeg-static'` there.

I don't know how declaring TypeScript types would affect the *runtime* behaviour of a pure JavaScript module. 🤔 It might theoretically be that TypeScript changes the behaviour of the [`__dirname` variable used](https://github.com/eugeneware/ffmpeg-static/blob/55975393f91e091a2083400477c18393f197a09e/index.js#L19) to be `''` though.

Unfortunately, I can't help you more.

**Comment by Timber1900** [comment]
## Some closing thoughts before I close this issue

- I think the problem lays on the optimization that react build creates, the reason the import is `/ffmpeg.exe` is because react *expects* it to be there, clearly something is going wrong and this fails

### The solution

- First we use `nw.require('ffmpeg-static')` so that we make sure we aren't using reacts version that points to the incorrect path but the regular one
- This works for `yarn start` but not `yarn build`, the latter will throw errors saying ` Cannot find module 'ffmpeg-static'`
  - To solve this we include the `node_modules/ffmpeg-static` folder on the `public` folder, this will ensure that the module is passed to the build, however this will not have automatic updates having to be mannualy updated when ffmpeg-static updates.

This was the only solution I came up with, it's a bit annoying but atleast it works.

Thanks @derhuerst for the help.

**Comment by mpirescarvalho** [comment]
I found a better solution.

Try playing arround with this config in your webpack config file:

```
node: {
    __dirname: false,
},
```

For me, setting it to true solved the issue, but others have reported that setting it to false worked for them, try it out.
