### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Thefrank** [eugeneware/ffmpeg-static#75]
trying to install anything that requires ffmpeg-static fails under FreeBSD as an example:

```
install bropat/ioBroker.eufy-security#6027c21fc25365e812ec5215336aede2783fbb0e
NPM version: 6.14.8
npm install bropat/ioBroker.eufy-security#6027c21fc25365e812ec5215336aede2783fbb0e --loglevel error --prefix "/opt/iobroker" (System call)
ffmpeg-static install failed: No binary found for architecture
npm ERR! code ELIFECYCLEnpm ERR! errno 1
npm ERR! ffmpeg-static@4.2.7 install: `node install.js`
npm ERR! Exit status 1npm ERR! npm ERR! Failed at the ffmpeg-static@4.2.7 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

what would it take to get that added? FreeBSD already offers it via pkg (pkg install ffmpeg) and ports (https://www.freshports.org/multimedia/ffmpeg/)

**Comment by derhuerst** [comment]
Thanks for reporting @Thefrank!

Currently, `ffmpeg-static` does not support FreeBSD. This can be changed by

- augmenting the [platform/arch detection logic](https://github.com/eugeneware/ffmpeg-static/blob/01200fe15056756ec8140653b0dbe8fc07cea9d6/index.js#L9-L16) to include `freebsd` (this is the value that [Node's `os.platform()`](https://nodejs.org/docs/latest-v10.x/api/os.html#os_os_platform) returns).
- augmenting the [binary download script](https://github.com/eugeneware/ffmpeg-static/blob/01200fe15056756ec8140653b0dbe8fc07cea9d6/build/index.sh) to download pre-built FreeBSD binaries.
- augmenting the [binary upload script](https://github.com/eugeneware/ffmpeg-static/blob/01200fe15056756ec8140653b0dbe8fc07cea9d6/.github/workflows/release-binaries.yml) upload the FreeBSD binaries.

Contributions welcome!

**Comment by Thefrank** [comment]
@derhuerst thanks for the reply!

node does seem to correctly detect the platform its on for freebsd:
```
Welcome to Node.js v15.5.1.
Type ".help" for more information.
> os.platform()
'freebsd'
> os.arch()
'x64'
```

I was able to build a statically linked ffmpeg for FreeBSD x64 (https://github.com/Thefrank/ffmpeg-static-freebsd) but was  unsure what codecs needed to be built into it so I guessed based on description, ports already in FreeBSD, and description.

Any guidance on this would be great!

**Comment by Thefrank** [comment]
> Cool! Did you upload the binaries somewhere?

I knew I forgot to post something! : https://github.com/Thefrank/ffmpeg-static-freebsd/releases/tag/v4.3.2
The actual binary is: https://github.com/Thefrank/ffmpeg-static-freebsd/releases/download/v4.3.2/ffmpeg
Compressing it (tar/gz/xz/bz2/whatever) would save bandwidth on the downloader but that would be it...it is just a single binary after all hah!

**Comment by derhuerst** [comment]
> The actual binary is: https://github.com/Thefrank/ffmpeg-static-freebsd/releases/download/v4.3.2/ffmpeg

I will adapt the [binary download script](https://github.com/eugeneware/ffmpeg-static/blob/1794103d9b2713a8c9da23207e970cda0a12db61/build/index.sh) to download it.

> Compressing it (tar/gz/xz/bz2/whatever) would save bandwidth on the downloader but that would be it...it is just a single binary after all hah!

Yeah, but that's the point: According to the GitHub API, `ffmpeg-static` has seen ~900k binary downloads (since I've switched to GitHub as binary host), so ~45tb of traffic. So I expect gzipping to save several terabytes of traffic.

The [binary publishing script does it](https://github.com/eugeneware/ffmpeg-static/blob/1794103d9b2713a8c9da23207e970cda0a12db61/.github/workflows/release-binaries.yml#L21-L27) anyway though, so you don't need to do that.

**Comment by derhuerst** [comment]
Published as `ffmpeg-static@4.3.0`. 🎉

I forgot to mention FreeBSD support in the readme, will do that in the next release.

**Comment by Thefrank** [comment]
Thanks for the addition!

**Comment by derhuerst** [comment]
Do you want to be mentioned as a contributor? If yes, with an email or website, or just as `Thefrank`?

**Comment by Thefrank** [comment]
Sure! `Thefrank` is plenty and if possible either my Github profile (https://github.com/Thefrank) or link to the repo for the binary (https://github.com/Thefrank/ffmpeg-static-freebsd). Hopefully that should be enough to draw people with binary specific issues to the binary repo and those with package issues to this repo hah

thanks again!
