### ISSUE TITLE
ffmpeg with x11grab support

### ISSUE THREAD

**Issue by ronerwix** [eugeneware/ffmpeg-static#77]
Hi, im trying to run the ffmpeg static with an x11 display and im getting an error:
Unknown input format: 'x11grab'
im running with version 4.3 and the command i'm trying to run is this:
./node_modules/ffmpeg-static/ffmpeg -y -video_size 1920x1080 -r 10 -f x11grab -i :125 -vf scale=640:360 -pix_fmt yuv420p ./test.mp4
from what i read online the fix was that the ffmpeg should be built with --enable-libxcb. im kind of new to ffmpeg so correct me if its a problem on my end, any help would be appreciated.
thanks.

**Comment by derhuerst** [comment]
At the top, the `ffmpeg --help` text will have the flags the binary has been built with; Check if `--enable-libxcb` is mentioned.

`ffmpeg-static` only intends to "distribute" pre-built binaries in a seamless way, it (currently) does not build the binaries. Contact the [binary providers]() to find out if they're willing to enable this flag. If they're not, you'll have to build ffmpeg yourself.

---

FYI You can also interact with the `ffmpeg` binary from `ffmpeg-static` this way:

```sh
$(node -p 'require("ffmpeg-static")') --help
```

**Comment by derhuerst** [comment]
Please re-open if you have more questions related to this topic!
