### ISSUE TITLE
High cpu usage on Windows but not on Linux.

### ISSUE THREAD

**Issue by Mike-Mp** [eugeneware/ffmpeg-static#84]
I'm testing an electron application that uses ytdl-core and ffmpeg-static to write audio/video in a users filesystem. On my Windows task manager, ffmpeg.exe reaches 100% of cpu usage. Why is that not the case on Linux and are there any fixes?

**Comment by derhuerst** [comment]
There are many possible reasons. Off the top of my mind:

- different hardware, e.g. with and without hardware acceleration, or
- different OS support for hardware acceleration, or
- different builds (`ffmpeg-static` just bundles binaries built by others, so they might be compiled with different flags).

Investigating is not within the scope of `ffmpeg-static` though. If you want to find out more, there are lots of resources on the internet that explain why `ffmpeg` is not as fast/efficient as desired.
