### ISSUE TITLE
Would it be possible to add librav1e?

### ISSUE THREAD

**Issue by Stryxus** [eugeneware/ffmpeg-static#89]
Im not an expert on licensing or anything and with AV1 (video codec) coming into the scene, iv been using libaom BUT it just doesnt cut it because it believe its single threaded and that with the high encoding complexity makes a 30s/60fps video take about half an hour to encode.

https://github.com/xiph/rav1e fixes this and is officially supported by ffmpeg but as far as I can see, it isnt built with the binaries which are provided here for whatever reason (might be licensing??). If its not licensing, would it be possible to somehow add extensions onto ffmpeg-static?

**Comment by Stryxus** [comment]
I believe they are just flags which are declared when ffmpeg is built, I know there are several different builds of ffmpeg for different licenses and librav1e is included in non-GPL compliant builds.

**Comment by derhuerst** [comment]
`ffmpeg-static` doesn't build its own binaries. Rather, we use the binary providers mentioned in the readme; You shoild try getting in touch with them.

The licensing issues still apply though.

**Comment by derhuerst** [comment]
Please reopen if your question hasn't been answered.
