### ISSUE TITLE
Failed installing ffmpeg-static 

### ISSUE THREAD

**Issue by JotaroKujo0525** [eugeneware/ffmpeg-static#90]
![Screenshot_20211015_124741](https://user-images.githubusercontent.com/77835007/137434279-1ea0c94a-219d-4aee-bf79-5352fceff081.jpg)

I was building myself a discord bot, and I'm currently hosting it on termux. I tried to install ffmpeg-static but this error happened

**Comment by derhuerst** [comment]
Which architecture and which platform are you trying to install `ffmpeg-static` on?
