### ISSUE TITLE
cannot open audio device default (No such file or directory)

### ISSUE THREAD

**Issue by mahmoudElgohary** [eugeneware/ffmpeg-static#94]
I'm try to run this commend 

`/node_modules/ffmpeg-static/ffmpeg -f alsa -ac 2 -i default -itsoffset '00:00:00.5' -f video4linux2 -s 320x240 -r 25 -i /dev/video0 'temp.mp4'"`

but get this error 
`ALSA lib ../../src/conf.c:3725:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/usr/lib/alsa-lib/libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib ../../../src/pcm/pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
[alsa @ 0x6342e00] cannot open audio device default (No such file or directory)
default: Input/output error
`
also I user ffmpeg to run it and run , any advice

**Comment by derhuerst** [comment]
This doesn't seem to be a problem with `ffmpeg-static`, and I cannot give support for ffmpeg itself here. You can get help with using ffmpeg via one of the [official support channels](https://ffmpeg.org/contact.html). Good luck!

In case an ffmpeg binary on your system (e.g. installed via your operating system's package manager) behaves differently than the ffmpeg binary from `ffmpeg-static`, please re-open this Issue.
