### ISSUE TITLE
Add FFmpeg 5.0

### ISSUE THREAD

**Issue by wolf-yuan-6115** [eugeneware/ffmpeg-static#96]
FFmpeg 5.0 is released now, but `ffmpeg-static` doesn't update yet.
These mirrors have FFmpeg 5.0:
- gyan.dev
- johnvansickle.com
- evermeet.cx
- osxexperts.net
- sudo-nautilus/FFmpeg-Builds-Win32

These mirrors **don't** have FFmpeg 5.0:
- thefrank/ffmpeg-static-Freebsd

***

Platforms already have FFmpeg 5.0 binaries:
- Windows (x64)
- Linux (All)
- Darwin (All)

Platforms **don't** have FFmpeg 5.0 binaries:
- Windows (ia32)
- FreeBSD

**Comment by derhuerst** [comment]
cc @sudo-nautilus @thefrank

**Comment by derhuerst** [comment]
What needs to be done from the `ffmpeg-static` side:

- [ ] wait until all mirrors are up-to-date
- [ ] adapt the [binary downloading script](https://github.com/eugeneware/ffmpeg-static/blob/8a8a4d376f09118fd2fc4ce8f171b3fa398ee55c/build/index.sh), if necessary
- [ ] push a `b5.0.0` tag, and let the CI download & re-publish the binaries to the GitHub release
- [ ] `package.json`: change the [GitHub release used](https://github.com/eugeneware/ffmpeg-static/blob/8a8a4d376f09118fd2fc4ce8f171b3fa398ee55c/package.json#L18-L19) & publish with a bumped `version`

**Comment by sudo-nautilus** [comment]
I believe that there are ffmpeg builds from the 5.0 branch, in my repo
![hmm](https://user-images.githubusercontent.com/78522210/150776730-e3fc81f8-1339-40fc-87ec-2000f1b4a6a1.jpg)

**Comment by wolf-yuan-6115** [comment]
> I believe that there are ffmpeg builds from the 5.0 branch, in my repo
> ![hmm](https://user-images.githubusercontent.com/78522210/150776730-e3fc81f8-1339-40fc-87ec-2000f1b4a6a1.jpg)
> 
Oof sorry, I didn't see that...

**Comment by Thefrank** [comment]
I am currently waiting on patches for FreeBSD to show up in ports :(

pending commit: 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261302
(I will give the patch here a try when I get some free time later this week)

**Comment by derhuerst** [comment]
@Thefrank any news? 🙂

**Comment by Thefrank** [comment]
It still has not even made it to FreeBSD ports.
At this point I don't think its fair holding up 99% of the user base.
You can drop support for now and once ffmpeg 5 is working under FreeBSD and I can get a static build of it, I can open a pull request to readd support.

Sorry about all of the delays here!

**Comment by wolf-yuan-6115** [comment]
> It still has not even made it to FreeBSD ports. At this point I don't think its fair holding up 99% of the user base. You can drop support for now and once ffmpeg 5 is working under FreeBSD and I can get a static build of it, I can open a pull request to readd support.
> 
> Sorry about all of the delays here!

Maybe this is better, why don't release FFmpeg 5.0? When user is using FreeBSD, then download FFmpeg 4.4 instead.

**Comment by tylerssn** [comment]
As an added thought here, would you be open to an MR (or this may require a fork) that implements this logic:

* Install ffmpeg latest stable 5: `yarn add ffmpeg-static@~5.0.0` _**OR**_ `yarn add ffmpeg-static@regular-semantic-version#5.0.0`

This would allow users to lock in the specific versions of ffmpeg that they require.

**Comment by derhuerst** [comment]
@tylerssn That already is a feature of all common package managers, right? There is [a not very detailed doc for Yarn](https://yarnpkg.com/cli/add) and [one for npm](https://docs.npmjs.com/about-semantic-versioning) on this.

**Comment by derhuerst** [comment]
@wolf-yuan-6115 @Thefrank I'll remove FreeBSD in `ffmpeg-static@5.0.0`, and we'll hopefully add it back later. People who need a FreeBSD will have to use `ffmpeg-static@^4` then.

**Comment by derhuerst** [comment]
Published as `ffmpeg-static@5.0.0`. 🎉

**Comment by tylerssn** [comment]
> @tylerssn That already is a feature of all common package managers, right? There is [a not very detailed doc for Yarn](https://yarnpkg.com/cli/add) and [one for npm](https://docs.npmjs.com/about-semantic-versioning) on this.

Of course 😺 . I was just proposing two options to go about it—use the normal semantic versioning, except the major number represents the FFmpeg version.

Or to use semantic versioning for the repository (`yarn add ffmpeg-static@repo-sem-ver` followed by `.ffmpeg-5.0`, resulting in: `yarn add ffmpeg-static@repo-sem-ver.ffmpeg-5.0`

Either way, thanks for the quick work on this!

**Comment by derhuerst** [comment]
> Of course 😺 . I was just proposing two options to go about it—use the normal semantic versioning, except the major number represents the FFmpeg version.

How would I upgrade the required Node.js version then, which is a breaking change, if no major ffmpeg version has been published?

> Or to use semantic versioning for the repository (`yarn add ffmpeg-static@repo-sem-ver` followed by `.ffmpeg-5.0`, resulting in: `yarn add ffmpeg-static@repo-sem-ver.ffmpeg-5.0`

But then all the built-in SemVer mechanisms don't work anymore (e.g. `npm upgrade ffmpeg-static`/`yarn upgrade`).  An option might be to use [dist tags](https://docs.npmjs.com/cli/v8/commands/npm-dist-tag) for this.

**Comment by tylerssn** [comment]
Looking at the dist tag docs, I don't think those will do the trick either.

Going back to what you actually implemented, that may be the win since this repo is literally `ffmpeg-static`. `yarn add ffmpeg-static@5.0` installs ffmpeg 5.0; `@4.0` installs 4.0, etc.

Thanks much for the work on this.

**Comment by derhuerst** [comment]
## 5.1.6

- [git tag](https://git.ffmpeg.org/gitweb/ffmpeg.git/tag/38c3847bed52de65dcd27bd7eeed86d1bc7eb440)

### ffmpeg

- [ ] Linux x64
- [ ] Linux x86
- [ ] Linux `arm`
- [ ] Linux `arm64`
- [ ] macOS x64
- [ ] macOS arm64
- [ ] Windows x64
- [ ] Windows x86
- [ ] FreeBSD

### ffprobe

- [ ] Linux x64
- [ ] Linux x86
- [ ] Linux `arm`
- [ ] Linux `arm64`
- [ ] macOS x64
- [ ] macOS arm64
- [ ] Windows x64
- [ ] Windows x86
- [ ] FreeBSD
