### ISSUE TITLE
published build includes (dev) dependencies?

### ISSUE THREAD

**Issue by mifi** [eugeneware/ffmpeg-static#98]
I can see that the published module includes some dependencies:
```
    "@derhuerst/http-basic": "^8.2.0",
    "env-paths": "^2.2.0",
    "https-proxy-agent": "^5.0.0",
    "progress": "^2.0.3"
```

https://unpkg.com/ffmpeg-static@4.4.1/package.json

I beleive those are only needed for running the build/publish, and will add unnecessary dependencies to the consuming project, so maybe should be moved to devDependencies?

**Comment by derhuerst** [comment]
They are needed for downloading the ffmpeg binary during installation of the npm package:

https://github.com/eugeneware/ffmpeg-static/blob/f6aef1a99733a01901572131c8940fa5e4a9378a/install.js#L7-L11

Does that answer your question?

**Comment by mifi** [comment]
Ah, makes sense. I forgot that this module changed the way it works, sorry! It's not optimal that it includes deps that are not really needed for ffmpeg, when using it in size-sensitive apps like apps built with Electron. But it should be possible to workaround it, maybe by removing these modules before packaging the app. Feel free to close.

**Comment by derhuerst** [comment]
> Ah, makes sense. I forgot that this module changed the way it works, sorry! It's not optimal that it includes deps that are not really needed for ffmpeg, when using it in size-sensitive apps like apps built with Electron.

Yeah, in general I'm not really happy with it, too. It seemed to be a reasonable trade-off, given that polluting the npm cache with n * 6 * 60mb of ffmpeg binaries is wasteful as well.

> But it should be possible to workaround it, maybe by removing these modules before packaging the app. Feel free to close.

Let me know if there's an Electron-specific way to signal that these dependencies can be pruned after the initial install!
